### ISSUE TITLE
Usage example does not work - result is undefined

### ISSUE THREAD

**Issue by silentrob** [philplckthun/node-tldr#7]
Demo is also not working.

**Comment by philplckthun** [comment]
This is not a bug! The module won't work with all websites, especially with those that do not comply to certain standards. Can you post the site you've tested node-tldr against?

**Comment by silentrob** [comment]
I believe it was a medium post. I feel like those should work.

**Comment by philplckthun** [comment]
Well not necessarily. They've got a really complex data model, as they're pulling data from their API. The HTML code itself doesn't obey to certain standards. Take a look at the source code yourself. I just didn't have medium.com in mind, when I developed this.

You should be able though, to integrate node-medium (another plugin of mine) into node-tldr.

https://github.com/philplckthun/node-medium
